apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spectis.fullname" . }}
  labels:
    {{- include "spectis.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret-key: {{ .Values.secrets.jwtSecretKey | quote }}
  database-url: {{ include "spectis.databaseUrl" . | quote }}
